Repository Tenderly/tenderly-cli, pull requests merged in 2022-01, with the labels that each got.

#63 Upgrade actions version to 0.0.6
  commands/actions/init.go
Labels: dependencies

#64 refactor: use `os.ReadDir` for lightweight directory reading
  brownie/config.go
  brownie/contract.go
  buidler/contract.go
  buidler/source.go
  commands/check_updates.go
  commands/util/filesystem.go
  config/config.go
  hardhat/contract.go
  hardhat/source.go
  jsonrpc2/http.go
  model/actions/template.go
  model/actions/util_test.go
  openzeppelin/config.go
  openzeppelin/contract.go
  openzeppelin/source.go
  rest/call/project.go
  rest/client/client.go
  truffle/contract.go
  truffle/source.go
  typescript/package.go
  typescript/tsconfig.go
  zip/zip.go
Labels: enhancement

#66 Fix go vet errors.
  ethereum/parity/types.go
  jsonrpc2/client.go
  rest/call/contract.go
  stacktrace/exception.go
Labels: invalid
